name: "Hall of Fame Addition"
description: "Add a Gato-X Discovery and to the Hall of Fame"
title: "Hall of Fame Entry - [REPOSITORY]"
labels: ['hall-of-fame']
assignees: 
  - AdnaneKhan
body:
- type: markdown
  attributes:
    value: "## Gato-X Hall of Fame Addition Request"
- type: textarea
  attributes:
    label: Fix Commit
    description: Link to the commit fixing the issue you reported.
  validations:
    required: true
- type: textarea
  attributes:
    label: Details
    description: Explain the Report and Impacted Open-Source Project
    placeholder: Details about the report, such as impact, interaction with maintainers.
    value: "Details"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Disclosure Type
    description: How did you report or fix the vulnerability?
    options:
      - Private Disclosure
      - Pull Request
- type: textarea
  attributes:
    label: Report Atribution
    description: Optional information attributing the fix to your report.
  validations:
    required: false
